# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

default_platform(:ios)

platform :ios do
  desc "Build iOS App"
  lane :build do
    match(type: "appstore", readonly: false, force_for_new_devices: true)

    gym(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.natify.natifyapp" => "match AppStore com.natify.natifyapp"
        },
        signingStyle: "automatic",
        teamID: "9PW89SQJ4U" # Remplace par ton Team ID Apple Developer
      }
    )
  end
end


